### ISSUE TITLE
Implement the Auth.js database model and its module

### ISSUE THREAD

**Issue by BracketJohn** [makerdao-ses/switchboard-boilerplate#10]
## Goal

Implement the Auth.js database model and its module

## Context

Depends on #9. We want to first implement the auth.js module and its related logic to get a feeling for it.

## Tasks

- [ ] add the User db schema from https://github.com/makerdao-ses/ecosystem-api/tree/main/src/modules/Auth to the prisma schema
- [ ] add the module logic from https://github.com/makerdao-ses/ecosystem-api/tree/main/src/modules/Auth module to this project
- [ ] open a PR to discuss what it looks like

**Comment by BracketJohn** [comment]
@KirillDogadin-std please take this one over (:

**Comment by KirillDogadin-std** [comment]
1. You mention `auth.js` module in the "context" section. Do you mean [this](https://github.com/makerdao-ses/ecosystem-api/tree/main/src/modules/Auth) with that term? do you mean https://authjs.dev ?
2. i assume [this](https://github.com/makerdao-ses/ecosystem-api/blob/main/src/modules/Auth/db.ts) is the "schema" of the database.
    - it references "role and permissions" 
    - there is no trace of roles or permissins found by me in the referenced module link
    - want me to do barebone user fields first? or should i look into comprehensive list of existing user-related tables as well?
3. add module logic from [this file](https://github.com/makerdao-ses/ecosystem-api/blob/main/src/modules/Auth/db.ts) as well? with all the "can*" functions?

**Comment by KirillDogadin-std** [comment]
- so apparently, in the initial repository "migrations" is a non-default concept.
  - migration files are adjusted via commits 
  - union of migration files resembles the database model (it seems)
    - no readme provided / found on this matter, so i might be missing some piece of info.

- i would move forward as follows in this case:
    1. implement the prisma model by migration [file](https://github.com/makerdao-ses/ecosystem-api/blob/main/migrations/20220916123447_release_202212.js): user, user roles, roles.
    2. create `helpers/api/auth/` and place a bunch of helper functions there that replicate the existing functionality in the existing repo and would be used later in the api middleware. 

___

is this sufficient? or should i build up the api structure in the same pr as well?

**Comment by KirillDogadin-std** [comment]
The source code stores `RolePermissions` in its own separate table,
The source code stores resourse that the permission is granted to in the column of the `RolePermissions` table as enum

Should we transfer this as well? it does not seem necessary. The permissions could be stored in the config file instead since the number of roles and the resource amount is limited. There's no reason to make queries to the db to find out the permission configs  (since this is repeatable and info set is small)

**Comment by valiafetisov** [comment]
> You mention auth.js module in the "context" section. Do you mean [this](https://github.com/makerdao-ses/ecosystem-api/tree/main/src/modules/Auth) with that term? do you mean https://authjs.dev/ ?

I think he meant [authjs.dev](https://authjs.dev/)

> want me to do barebone user fields first? or should i look into comprehensive list of existing user-related tables as well?

Yes, barebone. It should at least have [those fields](https://github.com/makerdao-ses/ecosystem-api/blob/8d5b9c84565a84e0047499af427b5d4ec9f751aa/src/modules/Auth/db.ts#L3-L7) (but they doesn't have to be called the same way)

> add module logic from [this file](https://github.com/makerdao-ses/ecosystem-api/blob/main/src/modules/Auth/db.ts) as well? with all the "can*" functions?

I think you can leave user roles out of the scope of this very first PR. This PR can just introduce authentication itself:  
- add tables required by they auth.js
- add authentication in the middleware level
- please note that access to the data stored in the database will always be public (except for the sessions/tokens, etc)
- protect existing endpoint from modification by the unauthenticated user
- If you already started working on the roles, you can also add them, but I think it might be more clear to do in the next PR

**Comment by KirillDogadin-std** [comment]
ok, then last question:

we don't have the api setup yet, do we? 

https://github.com/makerdao-ses/switchboard-boilerplate/blob/97e25d4b5dd618f13c868ca6fce9056bb2a6da42/package.json#L15-L17

what is the proposed structure of the api? what is the package?
do we use nuxt3 + h3 + auth.js + trpc ? something else?

**Comment by valiafetisov** [comment]
> we don't have the api setup yet, do we?

What is this then? https://github.com/makerdao-ses/switchboard-boilerplate/raw/main/.github/app.png

**Comment by valiafetisov** [comment]
The API have to be graphql-based. [Initially we planned for the `TypeGraphQL` on top of `TypeORM`](https://github.com/makerdao-ses/switchboard-boilerplate/issues/2), but since we started to experiment with Prisma, we might want to reevaluate that (although [TypeGraphQL also supports prisma](https://prisma.typegraphql.com/))

I think that means you can prioritise issue https://github.com/makerdao-ses/switchboard-boilerplate/issues/8 (which very much describes API requirement) over auth.

**Comment by BracketJohn** [comment]
> I think he meant [authjs.dev](https://authjs.dev/)

Just to jump in here: This is _not_ what I meant -> I was merely referencing the auth.js module name they used for their code. You can approach this any way you want / don't need to be bound by this tech decision

**Comment by valiafetisov** [comment]
@KirillDogadin-std Regarding how to provide auth info to the context and guard graphql endpoints, this [boilerplate](https://github.com/prisma-korea/prisma-nexus-apollo-boilerplate) can be a good _inspiration_. More specifically [context.ts#L93](https://github.com/prisma-korea/prisma-nexus-apollo-boilerplate/blob/c681f6c38eb0a18ed9f72d05e9ddde82a246832f/src/context.ts#L93) and [permissions/index.ts](https://github.com/prisma-korea/prisma-nexus-apollo-boilerplate/blob/main/src/permissions/index.ts)
