### ISSUE TITLE
Investigate logging libraries

### ISSUE THREAD

**Issue by LukSteib** [makerdao-ses/switchboard-boilerplate#17]
### Goal 
Research and decide on best logging library

### Context
We want to have an advanced logging library in place that allows to do error and performance logging. More input on original login requirement to inform the research: 
> should be able to toggle it, at least on a module level > to be plugged in to server logging infrastructure later

First library mentioned and that should be part of the investigation: [winston](https://github.com/winstonjs/winston)

### Tasks
- [x] Collect possible libraries
- [x] Propose qualities to make judgment
- [x] compare, discuss and conclude

**Comment by KirillDogadin-std** [comment]
- https://tslog.js.org/#/
  - can be toggled: yes - https://tslog.js.org/#/?id=changing-settings-at-runtime
  - error logging: yes - https://tslog.js.org/#/?id=default-log-level
  - performance logging: yes - https://tslog.js.org/#/?id=default-log-level
  - other features: https://tslog.js.org/#/?id=all-features
    - typed
    - pretty & json output
    - Pretty Errors
    - Named Loggers
    - Sub-loggers with inheritance
    - prefixes
  - gh stars: 1k
  - last update: last week https://github.com/fullstack-build/tslog

- https://github.com/winstonjs/winston
  - can be toggled: yes - https://github.com/winstonjs/winston#using-logging-levels
  - error logging: yes - https://github.com/winstonjs/winston#logging-levels
  - performance logging: yes - https://github.com/winstonjs/winston#logging-levels
  - ts support: seems so https://github.com/winstonjs/winston/blob/master/test/typescript-definitions.ts
  - other features https://github.com/winstonjs/winston#table-of-contents: 
    - custom logging levels
    - handling uncaught exceptions
    - custom formats
    - filtering of info objects
    - log querying
    - gh stars 20k
    - last update 8 feb
- https://www.npmjs.com/package/typescript-logging
  - can be toggled: seems no - https://github.com/vauxite-org/typescript-logging not mentioned in the docs
  - error logging: yes (supports various log levels such as debug)
  - performance logging: yes (supports various log levels such as debug)
  - additional features:
    - not mentioned
  - gh stars: 97
  - last update: last week

before i proceed: i would appreciate to have a more specific requirement set (what we need from the logging) because in other case it seems like we could just choose one of the most popular frameworks and use it (winston / tslog) without problems with such narrow requirement set.

**Comment by valiafetisov** [comment]
As specified in the issue description, main qualities are:
- Be able to select logging level, enable/disable
- Be able to enable logging per module (eg prefix and/or glob path support)
- Be able to plug output to the external service (although this should be possible without a special feature)

From my side I would add ease of use. But if all of the points are covered by winston, I think we can quickly conclude investigation and jump into adding it to the codebase 🙂

**Comment by valiafetisov** [comment]
Although there are also [Pino](https://github.com/pinojs/pino) and other which seem to be of the compared popularity https://www.highlight.io/blog/nodejs-logging-libraries. Maybe you can add them to the comparison as well?

**Comment by KirillDogadin-std** [comment]
added base param comparison: they're all the same,
seem to be equally ez/hard to use
winston leads in gh stars, last updated date. With such small set of things we would like to do with the logging lib, i would just choose winston based on these and the "fact" that the documentation there appears to be of high standard.

**Comment by valiafetisov** [comment]
I find `pino` to have a bit simpler interface and zero configuration, they also claim it's faster and have easy integration with [express](https://github.com/pinojs/pino/blob/master/docs/web.md#express) that we're using. One other big advantage I see is that pino works on the frontend as well. So I would try it first. Do you see any problem with that?


If you don't have any arguments against it, let's conclude it until you stumble upon something terrible 🙂 
- [ ] Install and configure it
- [ ] Add appropriate info/debug/error/etc logs to the codebase
  - [ ] To plain files
  - [ ] To http requests
- [ ] Forbid use of console via eslint rule
  - [ ] Can you maybe add a custom message to this error, suggesting use of a different library?
- [ ] Add short example usage to the `CONTRIBUTING` readme (let's create one in the root!)
- [ ] Make sure that in development it's nicely highlighted (ie via [pino-pretty](https://github.com/pinojs/pino-pretty))
