### ISSUE TITLE
Do not redefine db models for graphql

### ISSUE THREAD

**Issue by valiafetisov** [makerdao-ses/switchboard-boilerplate#18]
### Goal

Remove the need to define models again for nuxus

### Context

After merging https://github.com/makerdao-ses/switchboard-boilerplate/pull/15 the outstanding task was to explore possibility to derive nuxus types from the prisma model definition. [According to prisma graphl page](https://www.prisma.io/graphql), it should be easily integrable with graphql. To integrate with nuxus, they recommend [nexus-plugin-prisma](https://nexusjs.org/docs/plugins/prisma/overview) generator.

### Tasks
- [ ] Find the way forward
- [ ] Document investigation results
- [ ] Remove model definitions
