### ISSUE TITLE
SwitchboardAPI: Milestone

### ISSUE THREAD

**Issue by LukSteib** [makerdao-ses/switchboard-boilerplate#19]
### Scope: Milestone 1
- [ ] Setup a project with a linter and a prettier
- [ ] Setup ORM, declarative module structure
- [ ] Setup database migrations
- [ ] Setup something like [tsdoc](https://tsdoc.org/) (can be enforced via a linter rule)
- [ ] Setup tests for operations, models, database integration. Set high code coverage threshold early on
- [ ] Add CI steps to enforce tests, coverage, correct build outcome
- [ ] Add input validator (+possibly enforce its use via the config structure)
- [ ] Setup API playground (+possibly make database/code comments visible in the playground)
- [ ] Setup advanced logging library like [winston](https://github.com/winstonjs/winston), enforce correct usage (via a readme guide, linter settings)
- [ ] Implement authorization and authentication as a plugin/middleware
- [ ] Implement UI to login, create users and their API keys
- [ ] Add CD steps to build and deploy staging on merge to main
- [ ] Store history of every record
- [ ] Store change requests (endpoint path, parsed request body, reference to the record version it produced)
- [ ] Store attached files (as base64 or upload them somewhere)

**Comment by LukSteib** [comment]
WIP 

### Weekly Scope Planning KW 14

- [ ] Investigate graphQL playground alternatives
- [ ] Integrate document model jsdocs into UI
- [ ] #30
- [ ] Do POCs on schema language contenders
- [ ] Implement user management interface to UI

**Comment by LukSteib** [comment]
### Weekly Scope Planning KW 14

- [ ] #39(@KirillDogadin-std)
- [ ] #42 (@KirillDogadin-std)
- [ ] #41 (@KirillDogadin-std)
- [ ] #38 (@valiafetisov)
- [ ] #43
- [ ] #36 (@valiafetisov)

**Comment by LukSteib** [comment]
### Weekly Scope Planning KW 16

- [ ] #41 (@KirillDogadin-std)
- [ ] #43
- [ ] #36 (@valiafetisov)
