### ISSUE TITLE
Prepare the project to have UI

### ISSUE THREAD

**Issue by valiafetisov** [makerdao-ses/switchboard-boilerplate#27]
### Goal
The project displays a basic page with the project name and a link to the playground

### Context
We eventually want to have basic UI for user sign in and token generation, show documentation and graphql/sql playgrounds. 
But I also assume that we want to keep API codebase independent from the UI and keep it optional / modular. So we either need to create a separate frontend repo or turn this repo into monorepo. We also need to setup a project to work with modern frontend components (eg vue).

### Tasks
- [x] Propose concrete solution
- [x] Change structure of the project to be suitable for the frontend
- [x] Setup frontend
- [x] Setup proxy/middleware to serve both UI, API and playground
- [x] Make sure the readmes are updated accordingly 
- [x] Make sure the goal is reached
