### ISSUE TITLE
Research and coordinate document schema definition

### ISSUE THREAD

**Issue by valiafetisov** [makerdao-ses/switchboard-boilerplate#31]
### Goal
Agree on the document schema definition language

### Context
Since our API need to be build on top of the [document model structure developed in another repository](https://github.com/makerdao-ses/document-model-libs), we need to agree on what information is enough to be exported from that package in order to make integration smooth and maintainable in the future. For this, I would like to do a small research on what approaches are available, then discuss the outcomes.

### Tasks
- [ ] Outline overall integration requirements (ie what needs to be shared)
- [ ] Research schema definitions
  - [ ] Come up with a list of qualities to judge each contender
  - [ ] Propose possible contenders
- [ ] Ask for feedback
- [ ] Discuss externally
- [ ] Outline conclusion

**Comment by valiafetisov** [comment]
#### List of qualities to judge each contender
- Type safe
    - It should not be possible to define schema that doesn't fit models, operations
    - Schema validation at build time
- Extensible
    - Ideally, it should be possible to declare not only basic types, but also other parameters related to fields, eg initial/default values, validators (eg, to validate ethereum address or email), meta information (field title, field description, etc), relations, etc
- Reusable for database
    - In order to avoid redefining the structure of the data multiply times, the schema should hold information on relations (and their qualities). Otherwise, this will require double work on defining the schema and x4 work on migrating data (since the migrations then should be separately written for data and for the database)
- Support schema migrations
    - When a schema structure is updated, the database structure also needs to be updated, i.e. by generating a migration or writing it by hand. In case this is not included into the document model, it will need to be done manually at least two times

**Comment by valiafetisov** [comment]
### Possible contenders
- Typescript types (via something like [typescript-json-schema](https://github.com/YousefED/typescript-json-schema))
    - `+` Type safe
    - `+/-` Extensible
        - Typescript types are not available at runtime. However it's possible to compile them to json-schema [via external libraries](https://github.com/YousefED/typescript-json-schema#annotations). The library also supports using jsdoc-style comments to extend types with extra data, altrough this might be too hacky
    - `-` Reusable for database
        - Unless we try to squeeze database types into jsdoc
    - `-` Support schema migrations
- JSON schema (via something like [ajv](https://ajv.js.org/))
    - `+/-` Type safe
        - `-` Limited [support](https://ajv.js.org/guide/typescript.html#additional-functionality) for type safety of the schema itself if declared within typescript
            - Limited due to no type support for [metadata declaration](https://ajv.js.org/json-type-definition.html#user-defined-keywords) in tooling
        - `+` Possible to create validators / type guards
    - `+` Extensible
        - Already supports description of fields
        - Possible to extend schema with metadata/user-defined keys
    - `-` Reusable for database
    - `-` Support schema migrations
- GraphQL schema language (using [codegen](https://the-guild.dev/graphql/codegen))
    - `-` Type safe
        - Or at least until the schema is the ultimate source of truth and types are generated from it
        - The extensions are not type safe (eg `@constraint` mentioned below can not be safely validated while editing or at build time)
    - `+/-` Extensible
        - It's technically possible to extend schema statically via something like a custom `directive`
        - Declarative-only, example [`@constraint` directive](https://www.apollographql.com/blog/backend/validation/graphql-validation-using-directives/)
            - This `modifies GraphQL schema, basic scalars (Int, Float, String) are replaced by custom scalars`
    - `+/-` Reusable for database
        - As mentioned above, it's technically possible to extend schema with a custom directive that will be interpreted by a custom codegen
    - `-` Support schema migrations
    - Overall
        - It does seems strange to define schema in another language to then generate something usable from it to then later on generate actual schema for typescript
- [Typeorm](https://typeorm.io/) models definition (together with something like [typeorm-polymorphic](https://github.com/bashleigh/typeorm-polymorphic))
    - `+/-` Type safe
        - The only missing type safety in typeorm is inability to validate db type over the ts type (due to limited ts support for decorators)
    - `+` Extensible
        - New decorators as well as arbitary methods can be added to the schema
    - `+` Reusable for database
        - As it defines database model itself, it can be used both on frontend using in-memory sqlite as well as for the API
    - `+` Support schema migrations
        - If changes are made to the schema itself, it's easy to automatically generate migrations (on the API side, where we care about consistency) and ignore this part on the frontend

**Comment by valiafetisov** [comment]
> we would have to also migrate the history of changes (operations) which are stored (i assume) in the database

No, there is no such requirement, to my knowledge. We would only need to migrate the state, not operations. Each operation will store parameters passed to it as json, unstructured. I general I think it wouldn't make sense to migrate operations, since, for example it's possible that some operation that exist today will not exist in the future – this doesn't mean we need to remove it from the table of executed operations 🙂

**Comment by BracketJohn** [comment]
Thanks for the investigation.

The setup would be:
- doc model team writes typeORM models that represents their data
- doc model team uses models as typing-indicators in their DB
- doc model team shares packaged typeORM models with switchboard api team
- switchboard api team uses typeORM models to:
  - provide API
  - setup & run DB
  - implement auth
  - ...

Qs:
- I guess this would force us to use https://github.com/typestack/class-validator if we want to have runtime-data-validation, e.g., on the API level, instead of zod?
- would graphql be generated from typeORM models somehow?
