### ISSUE TITLE
Create health check endpoints

### ISSUE THREAD

**Issue by valiafetisov** [makerdao-ses/switchboard-boilerplate#33]
### Goal
Both of our services have `/api/healthz` get endpoints

### Context
https://github.com/makerdao-ses/switchboard-boilerplate/issues/30#issuecomment-1490396595

### Tasks
- [ ] Add `/api/healthz` endpoint to `api`
  - [ ] Make sure this endpoint connects to the database
- [ ] Add `/api/healthz` endpoint to `frontend`
- [ ] Add small note about them in the respective readmes

**Comment by KirillDogadin-std** [comment]
>  Add /api/healthz endpoint to frontend

i'm struggling to understand what you mean by this. What is the user story here?
should frontend have its own api? should it just show a component with health? redirect response from the api?

**Comment by valiafetisov** [comment]
> What is the user story here?

I hoped that would be explained by the wording and the link under the context section. Kubernets needs something reachable in order to determine if it's alive or not. Therefore, the frontend (which is running a server anyway to serve html) also need to have similar endpoint, although it doesn't need to reach to the database or anywhere else

**Comment by valiafetisov** [comment]
Yeah, I guess it's fine to query a table (and not return anything from the endpoint) to better validate that prisma client is properly initiated
