### ISSUE TITLE
Agree on auth, roles and permissions

### ISSUE THREAD

**Issue by valiafetisov** [makerdao-ses/switchboard-boilerplate#36]
### Goal
Agree on the overall functionality related to auth

### Context
Since the initial version of the authentication was already implemented in #16 and #28, it's time to make it production-ready and close all open questions.

### Tasks
- [ ] Prepare all open questions
- [ ] Propose an answer to each question
- [ ] Ask for feedback
- [ ] Conclude

**Comment by valiafetisov** [comment]
1. Who is able to fetch data?
    - Proposal: In order to make requests, one have to register and send authorization token with every request
        - Reason: in order to prevent potential distributed denial-of-service attacks, we need to identify each request, this will also help us identify who is using the API
2. Who is able to register?
    - Proposal: registration is open for everyone, once account is created, the user can immediately make get requests
        - Reason: we anyway plan to make database dump publicly available, and make operations transparent
3. What external service will be used to confirm registration (email, captcha, etc)? (we need that in order to protect from ddos attacks and provide "password reset" functionality)
    - Proposal: users should be able to register using their email
        - Reason: Email is a decentralized protocol, although still commonly used and is suitable for non-technical users (ie analysts). later on we can also support [Sign-In with Ethereum](https://eips.ethereum.org/EIPS/eip-4361) functionality interchangeably
4. Do we need to set origin restrictions for tokens?
    - Proposal: yes
        - Reason: since we expect that many requests will be coming from other frontend that publicly expose our tokens, this is essential to prevent token stealing
6. Do we need to distinguish between read and write tokens?
    - Proposal: Maybe in the long-term
        - Reason: The user who creates the token will give the token the same rights as the user itself (as in many other services)
5. How will the rights be distributed and by whom?
    - Proposals: 
      - a) There will be a special role to edit all user roles
      - b) There will be a user document model with special operations to add or remove roles, different roles will allow editing of different users
7. How will other frontends get auth information from us? Will they implement their own login forms (and trust other websites to put their passwords in)? Or will we need to provide SSO-like functionality?

**Comment by valiafetisov** [comment]
### Reaction to [Permissioned_Document_Processes.pdf](https://github.com/makerdao-ses/switchboard-boilerplate/files/11252310/a9de28e7-4cec-4725-8aff-4170557bddbb_Permissioned_Document_Processes.pdf):

> For each state (`External`, `Draft`, and `Final`), there is a `TO_{STATE}` permission that can be assigned.

- This approach is hardly generic. For example,  there can be a new requirement in the future to restrict `Core Unit Administrator`s from changing `Final` to `Draft`, which would require adding 9(?) other new rights
- This level of granularity is still not sufficient to make permissions completely static. For example: it does not cover ownership of the document (or can `Core Unit Administrator` edit any `Budget Statement` in `Draft` state?). Therefore, the "ownership" check (or rather check that the document is attached to the same Core Unit as `Core Unit Administrator`) would still need to be written in code, inside document model (or its permission layer, up to you)
    - Or, if it's desired to make those checks static (computable without execution) you would need to adopt some existing generic approach to defining checks like ownership (e.g. json schema)

Based on the above, I would propose to:
- Define a list of roles that are static (eg `CORE_UNIT_ADMINISTRATOR`, `CORE_UNIT_AUDITOR`, etc)
    - Export the list from the document model
- Attach those "roles" to a user, store them in the database
- When editing the document, send user object with
    - List of attached roles
    - Complete user object (eg. which core units are attached to it)
- Do the actual check in the document model code

Based on the proposal, we need to agree on:
- [ ] Under which name/path the list of roles is exported from the `document-model-libs`
- [ ] Under which key the list of user roles is sent to the document model (eg `roles`)
- [ ] What format is used to send related information
- [ ] What to do when previously existing roles are removed (i.e. migrations)

**Comment by valiafetisov** [comment]
### Reaction to [Authentication_and_Message_Signing.pdf](https://github.com/makerdao-ses/switchboard-boilerplate/files/11252509/fb8b3f01-0966-4a5a-9012-27538953c24c_Authentication_and_Message_Signing.pdf)

In progress
