### ISSUE TITLE
Setup repository

### ISSUE THREAD

**Issue by valiafetisov** [makerdao-ses/switchboard-boilerplate#4]
### Goal

Repository is ready for work and adheres to our standards

### Tasks

- [x] Setup merge rules (was done by @valiafetisov)
- [ ] Setup main branch protection (or give @valiafetisov enough rights)
- [x] Enable CI via github/drone

**Comment by BracketJohn** [comment]
>  Setup main branch protection (or give @valiafetisov enough rights)

For this one we will have to ask @wkampmann as we do not have enough rights. I'll move it to a new issue so that we can close this one:
- [ ] Setup main branch protection
