### ISSUE TITLE
Implement optional token restriction by origin

### ISSUE THREAD

**Issue by LukSteib** [makerdao-ses/switchboard-boilerplate#41]
### Goal
User can restrict the token by origin

### Context
During UI conceptualization and thoughts on auth introduced the requirement for optional origin restriction of tokens.
The mock below shows how we'll implement origin restriction possibility into the UI. 
The user will be able to specify origin URL and all requests coming with this token but having another origin will be blocked

### Assets
<img width="650" alt="image" src="https://user-images.githubusercontent.com/36229155/230094480-469af28a-0384-4ba3-8eae-d50e30c48255.png">

### Tasks
- [x] Implement functionality to restrict tokens by origin
   - [x] default value: no origin restriction at all
- [x] ensure that requests of token that is restricted but coming from different origin fail

**Comment by valiafetisov** [comment]
- Please validate provided origin during creation
  - Make sure that it can include schema (eg `http` or `https`)
  - Do not accept null, explicitly require `*` instead for unrestricted keys (and please throw readable error about that)
  - Accept comma-separated array
- Please validate token access on `getUser`
  - Make sure validation logic supports wildcards, eg https://www.npmjs.com/package/match-url-wildcard (there should be a better package, as this one looks outdated, eg https://www.npmjs.com/package/wildcard)
