### ISSUE TITLE
Document potential UX improvements for documentation

### ISSUE THREAD

**Issue by LukSteib** [makerdao-ses/switchboard-boilerplate#48]
### Goal
Improve UX of documentation page

### Context
With #42 documentation was introduced. 
With this issue we want to collect and tackle potential improvements

### Assets
List of things noticed
- [x] viewport once sidepanel navigation changes so that user first has to horizontally scroll in order to see side panel again (see r1)
- [x] would be nice to have a visual indication (e.g. color highlighting) on current position in side panel navigation
- [x] the title element of the whole application is now called `Readme` (see s1)

r1
https://www.loom.com/share/7100205cdcda4b3a9a063f77b26083ba

s1
<img width="200" alt="image" src="https://user-images.githubusercontent.com/36229155/232037653-a8838b07-2a93-4ca8-9481-cfd17bebf586.png">

### Tasks
- [x] Tackle points outlined above

**Comment by valiafetisov** [comment]
- [ ] It would be nice to show version of the package (but this can only be added once it's integrated via npm)
