### ISSUE TITLE
Setup linter

### ISSUE THREAD

**Issue by valiafetisov** [makerdao-ses/switchboard-boilerplate#5]
### Goal

Repository contains linting and prettier rules validated via CI

### Tasks

- [ ] Choose prominent linting rule set
- [ ] Setup linter
- [ ] Setup prettier to match linting rules
- [ ] Setup `.editorconfig` to match linting rules
- [ ] Setup CI check via github/drone
- [ ] Setup pre-commit hook

**Comment by BracketJohn** [comment]
>  Choose prominent linting rule set

went for airbnb, but without the react rules!

>  Setup prettier to match linting rules

I would vouch against using prettier. Instead let's use eslint + typescript to achieve everything we want to achieve.

>  Setup CI check via github/drone

done via github (: See eg: https://github.com/makerdao-ses/switchboard-boilerplate/actions/runs/4306069096/jobs/7509389258

>  Setup pre-commit hook

I'd actually also be against using pre-commit hooks. In the past it has caused a worse DX for little gain + the setup always feels quite brittle (not correctly installing for some devs who then don't use it by accident). What do you think?
