### ISSUE TITLE
Create graphql setup

### ISSUE THREAD

**Issue by BracketJohn** [makerdao-ses/switchboard-boilerplate#8]
## Goal

Setup prisma ORM  + a graphql API provider.

## Context 

Out of #3 and #2 we want to setup prisma and a graphql api provider (such as apollo, as used here: https://github.com/makerdao-ses/ecosystem-api/blob/main/src/index.ts) to get the project started.

## Tasks

- [ ] research which gql provider to use
  - [ ] prisma has their own examples that we can probably just take over 
    - [ ] (https://github.com/prisma/prisma-examples)
    - [ ] https://github.com/prisma/prisma-examples/tree/latest/typescript
- [ ] setup prisma and the graphql provider
- [ ] add a hello world model to prisma database
- [ ] ensure that the following works:
  - [ ] prisma schema generation
  - [ ] graphql schema / types generation
  - [ ] a graphql playground

**Comment by valiafetisov** [comment]
[TypeGraphQL also supports prisma](https://prisma.typegraphql.com/)), so would be great to see it in the research comparison

**Comment by KirillDogadin-std** [comment]
1. [Nexus](https://github.com/prisma/prisma-examples/tree/latest/typescript/graphql-nexus)
    - uses:
      - [Apollo Server](https://github.com/apollographql/apollo-server)
      - [GraphQL Nexus](https://nexusjs.org/docs/)
    - downsides:
      - no previous xp of the team
    - upsides:
      -  some similarity with how zod defines schemas [link](https://github.com/prisma/prisma-examples/blob/latest/typescript/graphql-nexus/src/schema.ts)
      - derives graphql return structure from prisma types.
2. [NestJs](https://github.com/prisma/prisma-examples/tree/latest/typescript/graphql-nestjs)
    - uses:
      - [NestJs](https://docs.nestjs.com/graphql/quick-start)
    - downsides:
      - nit: looks like too much space is taken up by boilerplate [e.g.](https://github.com/prisma/prisma-examples/blob/latest/typescript/graphql-nestjs/src/resolvers.post.ts)
      - nit: decorators is an experimental feature [as here](https://github.com/tc39/proposal-decorators)
      - no previous xp of the team
      - within this example: the setup does not derive graphql return structure from prisma code
    - upsides:
      - can infer routes from file location and name
      - single dependency
3. [Hapi](https://github.com/prisma/prisma-examples/tree/latest/typescript/graphql-hapi)
    - modification of (1) with [hapi](https://hapi.dev)
4. [fastify](https://github.com/prisma/prisma-examples/tree/latest/typescript/graphql-fastify)
    - schema: as in (1), hence pros and cons are derived from there
5. [type graphql](https://prisma.typegraphql.com)
    - as of documentation is compatible with nest-js
    - upsides:
      - automatically generated graphql types
    - downsides:
      - docs only feature nestjs api in combination with the [package](https://github.com/MichalLytek/typegraphql-prisma/tree/main/examples/4-nest-js).

Conclusion:

  - I would say that avoiding duplication of the information (db model, graphql model) is desirable. Therefore (2) is out
  - (4), (3), (1) are similar and are different from each other essentially by api framework choice
  - (5) unlike the options from the point above uses nest.js . It introduces the possibility to use more declarative style of endpoint & schema definitions. E.g. [this style](https://github.com/prisma/prisma-examples/blob/15af3868f1e00b03a04a5e86cabdc152db498686/typescript/graphql-nexus/src/schema.ts#L227-L234) vs [the other one](https://github.com/MichalLytek/typegraphql-prisma/blob/a45a0a5694ad9b6ae0ea3cf4552f4500f1532d5e/examples/4-nest-js/index.ts#L39-L40)


Since there's a discussion to take a place about switching to TypeORM, i will leave the current state of investigation. 

If we remain with Prisma, the next step would be to play around with the api setups:

How does ... work?:
  - middleware injection
  - complex queries
  - validation
  - playground for the api (e.g. swagger)
