### ISSUE TITLE
Setup Prisma ORM

### ISSUE THREAD

**Issue by BracketJohn** [makerdao-ses/switchboard-boilerplate#9]
## Goal

Setup prisma db for this project.

## Context

Based on #2 and #3 we want to use Prisma, as it takes over the typescript type generation for our model based on a compact schema. We can then expand the database in a modular structure through the prisma extends-functionality.

## Tasks

- [ ] setup prisma
  - [ ] hello world schema
  - [ ] commands in package.json
  - [ ] db-playground `npm run prisma studio` is working
